apiVersion: storage.kubestash.com/v1alpha1
kind: RetentionPolicy
metadata:
  name: retention-policy
  namespace: demo
spec:
  maxRetentionPeriod: 2mo
  successfulSnapshots:
    last: 10
  usagePolicy:
    allowedNamespaces:
      from: All
